spring:
  application:
    name: bank1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rqbank1
    username: root
    password: 123456
server:
  port: 8081
  servlet:
    context-path: /bank1
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka
    register-with-eureka: true
    fetch-registry: true
rocketmq:
#  producer:
#    group: producer_bank2
  name-server: localhost:9876